### ISSUE TITLE
How to get Consumption based on "before:" or "after:" for specific date as reference?

### ISSUE THREAD

**Issue by rluebess** [tibber/Tibber.SDK.NET#10]
I need to export the consumption-data for specific months
But it seems I can only limit the count of consumtion nodes by quantity:

```
.WithHome(
                        new HomeQueryBuilder()
                            .WithConsumption(
                               resolution: EnergyResolution.Hourly,
                               lastEntries:1000
                            )
 ...
```

but how can i add the use the date function "before" or "after" to speciy certain reference date?

**Comment by toini** [comment]
You can pass the cursor value as a Base64-encoded ISO8601 date/time. See https://developer.tibber.com/docs/reference.
