### ISSUE TITLE
How to provide PV power using API

### ISSUE THREAD

**Issue by c0ldtech** [tibber/Tibber.SDK.NET#11]
Hello everyone,

I have a Sungrow solar inverter. Sungrow is not supported in Tibber yet, and I also do not want to export my solar data to a chinese cloud - so if Sungrow would ever be supported, I guess it would be through connecting to the Sungrow cloud.

Is it possible to provide solar production to Tibber using the API? So I can provide current production values of the inverter by myself through the API? This would basically open up all kinds of inverters for use with Tibber. Since it does not have any influence on actual consumption from the grid and therefore anything that is related to cost, this should be a risk-free feature for the Tibber API. I just really would like to see my solar production data in the Tibber App.

Best regards
Hendrik

**Comment by toini** [comment]
Hi @c0ldtech,

Unfortunately it is not possible to feed in solar production via the API and we don't have any plans on adding that. On the other hand, I do see that adding support for Sungrow inverters is in the pipeline (but there is no timeline I could commit to).

Br,
Toni
Tibber
