### ISSUE TITLE
Consumption Values always one hour in the past

### ISSUE THREAD

**Issue by tarres** [tibber/Tibber.SDK.NET#13]
When I request the consumption values the list always stops at one hour in the past:
Example
```                
                        new TibberQueryBuilder()
                            .WithViewer(
                                new ViewerQueryBuilder()
                                    .WithHome(
                                        new HomeQueryBuilder()
                                            .WithConsumption(EnergyResolution.Hourly, 1),
                                        homeId
                                    )
                            );
```
When I run this code at 08:15 the newest node value I get is in timeframe 07 to 08.

**Comment by tarres** [comment]
No, in the explorer it shows the correct values with the sample query. I posted the query builder above, what else do you need?

**Comment by toini** [comment]
I was hoping you could share the actual Graphql query being executed that I could run in the explorer? The result should be indentical as it's coming from the same service. Maybe you could also share the result 1. from Tibber.SDK.NET and 2. from [developer.tibber.com/explorer](https://developer.tibber.com/explorer)?

**Comment by tarres** [comment]
I see: here is the query:
`{viewer{home(id:"<guid>"){consumption(resolution:HOURLY,last:2){nodes{from,to,unitPrice,unitPriceVAT,consumption,consumptionUnit,cost,currency}}}}}`
It produces the same result in the explorer.
Here a result from today ~15:50
```
{
  "data": {
    "viewer": {
      "homes": [
        {
          "consumption": {
            "nodes": [
              {
                "from": "2023-11-08T13:00:00.000+01:00",
                "to": "2023-11-08T14:00:00.000+01:00",
                "cost": null,
                "unitPrice": 0.xxxx,
                "unitPriceVAT": 0.xxxx,
                "consumption": null,
                "consumptionUnit": "kWh"
              },
              {
                "from": "2023-11-08T14:00:00.000+01:00",
                "to": "2023-11-08T15:00:00.000+01:00",
                "cost": null,
                "unitPrice": 0.xxxx,
                "unitPriceVAT": 0.xxxx,
                "consumption": null,
                "consumptionUnit": "kWh"
              }
            ]
          }
        }
      ]
    }
  }
}

**Comment by tarres** [comment]
Ah I need subscription not consumption
