### ISSUE TITLE
Issue with listener

### ISSUE THREAD

**Issue by centpede** [tibber/Tibber.SDK.NET#14]
Dear Toni,

Thank you for this piece of  high-level C# art! I've tried to use the SDK, but had no luck with the Listener using the examples from the readme.

XXXXX..... is in real replaced with the correct values.

```
var userAgent = new ProductInfoHeaderValue("RobinTibber", "1.0");
var client = new TibberApiClient("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", userAgent);
var homeId = Guid.Parse("XXXXXXXXXXXXXXXXXXXXXXX");
var listener = await client.StartRealTimeMeasurementListener(homeId);
listener.Subscribe(new RealTimeMeasurementObserver());

// Listen for a bit
await Task.Delay(TimeSpan.FromSeconds(600));

Console.WriteLine("Stop listening");

// Stop listening
await client.StopRealTimeMeasurementListener(homeId);


public class RealTimeMeasurementObserver : IObserver<RealTimeMeasurement>
{
    public void OnCompleted() => Console.WriteLine("Real time measurement stream has been terminated. ");
    public void OnError(Exception error) => Console.WriteLine($"An error occured: {error}");
    public void OnNext(RealTimeMeasurement value) =>
        Console.WriteLine($"{value.Timestamp} - power: {value.Power:N0} W (average: {value.AveragePower:N0} W); consumption since last midnight: {value.AccumulatedConsumption:N3} kWh; cost since last midnight: {value.AccumulatedCost:N2} {value.Currency}");
}`
```

Last Tracing entry:
`subscribe to XXXXXXXXXXXXXXXXXXXXXXXXX`

Last method (RealTimeMeasurementListener.cs):
`StartListening()`

The error seems to be here (RealTimeMeasurementListener.cs):
`Line 298 stringRecords	"{\"id\":\"1\",\"type\":\"next\",\"payload\":{\"errors\":[{\"message\":\"Cannot read private member #context from an object whose class did not declare it\",\"locations\":[{\"line\":1,\"column\":14}],\"path\":[\"liveMeasurement\"]}]}}"	string
`

Exception goes here (RealTimeMeasurementListener.cs):
`Line 266: $exception	{"The remote party closed the WebSocket connection without completing the close handshake."}	System.Net.WebSockets.WebSocketException`

Any idea what is going wrong?

Thanks,
Robin

**Comment by toini** [comment]
The error seems to be coming deep from the server and looks quite weird. We will need to take a look when back at office. This is your first time trying the API? Does the explorer at developer.tibber.com work fine for you?

**Comment by centpede** [comment]
Dear Toni,
yes, this is the first time I'm using the API with C#. But I already have a working API-solution build with Powershell.

**Comment by centpede** [comment]
Dear Toni,

please close the issue, this was my stupidity. After checking my powershell solution I see that a wrong home ID was used.
Sorry for bothering you.

**Comment by toini** [comment]
No worries! Good thing you got it working :)
