### ISSUE TITLE
Unregistering GraphQL subscriptions

### ISSUE THREAD

**Issue by stefanes** [tibber/Tibber.SDK.NET#4]
Reading the documentation [here](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md), should this not be a `complete` message instead?

https://github.com/tibber/Tibber.SDK.NET/blob/22bd5da24893be58c19422088ec69e6c410a1b4c/src/Tibber.Sdk/RealTimeMeasurementListener.cs#L190

**Comment by toini** [comment]
Yeah, you are absolutely right. However, it seems [graphql-ws](https://github.com/enisdenjo/graphql-ws) interprets `stop` the same way as `complete` so it does work. Funnily, even a message with type `xxxxx` is interpret as complete (I just tried with debugger).

I'll push a fix to correct the messsage type anyways.

**Comment by toini** [comment]
And thanks for spotting it!
