### ISSUE TITLE
getting no response after ack from websocket

### ISSUE THREAD

**Issue by humpataa** [tibber/Tibber.SDK.NET#9]
Hello,

I am trying to get a simple Javascript websocket query working, but having difficulties. This is my code so far:

```
host = 'wss://websocket-api.tibber.com/v1-beta/gql/subscriptions';
let ws = new WebSocket(host, 'graphql-transport-ws');

ws.onopen = function(){
	json= '{"type":"connection_init","payload":{"token":"5K4MVS-OjfWhK_4yrjOlFe1F6kJXPVf7eQYggo8ebAE"}}';
	ws.send(json)
}

ws.onmessage = function(msg) {
	console.log(msg)
	reply = JSON.parse(msg.data)
	if (reply["type"] == "connection_ack") {
		console.log("ack!")
		json = '{"id":"acf63a4c-bc2f-4010-b5b5-7897e90f7702","type":"subscribe","payload":{"variables":{},"extensions":{},"query":"subscription {liveMeasurement(homeId: \'96a14971-525a-4420-aae9-e5aedaa129ff\') {timestamp}}"}}';
		ws.send(json)
	}
	//console.log(ws)
}


ws.addEventListener('error', (event) => {
  console.log('WebSocket error: ', event);
});
```

I can see in browser's network traffic that it gets "connection_ack" back but no reply after sending the subscription. I believe something is wrong with the json string at "homeId": when I try to mask it with \\" it isn't being sent at all. No masking doesn't work either. Or maybe it is because of the id? Two questions:

1. what is the id and where to get it? the first reply (ack) does not include an id. is it free to choose? any fixed format?
2. how do I mask the homeId correctly?

Any help is greatly appreciated!

**Comment by humpataa** [comment]
One more try didn't help either ... subscription json gets sent, but no reply:

`{"id":"acf63a4c-bc2f-4010-b5b5-7897e90f7702","type":"subscribe","payload":{"variables":{},"extensions":{},"query":"subscription {liveMeasurement(homeId: \"96a14971-525a-4420-aae9-e5aedaa129ff\") {timestamp}}"}}`

<img width="1637" alt="Bildschirmfoto 2023-02-24 um 16 57 20" src="https://user-images.githubusercontent.com/45576905/221225736-ac49020b-52d2-4dd6-ac28-48d58f10c65c.png">

**Comment by toini** [comment]
Have you considered using Apollo's client like in [Homey app](https://github.com/tibber/com.tibber.athom/blob/master/lib/tibber.ts#L364])?

**Comment by toini** [comment]
The last message you are sending looks malformed? See {timestamp} in the end.

**Comment by toini** [comment]
You easily can compare to working messages at https://developer.tibber.com/explorer
![image](https://user-images.githubusercontent.com/7605167/221536794-16a96045-8b67-478f-8271-9a8b611a4f81.png)

**Comment by humpataa** [comment]
Thank you for getting back. I actually had to mask the homeId twice. Also, the id is not any random number. It would be nice if the API documents would provide info on that. Took me hours if not days.
Anyway, it's working now and I have made it public so others can check: https://github.com/humpataa/tibber-liveMeasurement

**Comment by toini** [comment]
@humpataa do you mean that you missed that the homeId parameter must be your home id? Did you see https://developer.tibber.com/docs/reference and https://developer.tibber.com/docs/guides/calling-api

**Comment by humpataa** [comment]
@toini, excuse me, have you actually read what I wrote above?
Of course I did use homeId, I have exactly studied network traffic etc. my question was: how to mask the homeId. After hours of trying I have found the right way to do it. Next question was about the correct "style" of the id - no info on that in the docs, no info elsewhere.

**Comment by toini** [comment]
@humpataa i did try to read it several times but for some reason i dont still understand, sorry. What exactly do you mean by "masking the homeId"?

**Comment by humpataa** [comment]
With "masking" I meant preparing the json correctly for the websocket to understand.
First try (not working, although correct json syntax): "query":"subscription {liveMeasurement(homeId: \'96a14971-525a-4420-aae9-e5aedaa129ff\') {timestamp}}"
Second (not working, although correct json syntax) : "query":"subscription {liveMeasurement(homeId: \"96a14971-525a-4420-aae9-e5aedaa129ff\") {timestamp}}"
Third (finally working): "query":"subscription {liveMeasurement(homeId: \\\"96a14971-525a-4420-aae9-e5aedaa129ff\\\") {timestamp}}"
Same goes for the used id in requests. Unfortunately, the servers does not respond with messages telling what's wrong or missing. And the docs don't say exactly what is needed or give examples either. So it was very hard to find the solution.
Thank you for getting back. I think we can close this now. Maybe add some detailed info on this matter to the dev docs.
